name: Publish Package to GitHub and create a Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build Package
        run: gradle build && gradle shadowJar
      - name: Publish Package
        run: gradle publish
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_URL_RELEASES: ${{ secrets.MAVEN_URL_RELEASES }}
          MAVEN_URL_SNAPSHOTS: ${{ secrets.MAVEN_URL_SNAPSHOTS }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Delete the oldest Package Version
        uses: actions/delete-package-versions@v1
        with:
          package-name: "de.codemakers.cjp-database"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          artifacts: "build/libs/*.jar,dist/*.jar"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
